version: '3'
services:
  routine_db:
    build:
      context: ../
      dockerfile: ./docker_builds/DockerFileDB
    container_name: routineDB
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - --character-set-server=utf8
    networks:
      - routine_net

  routine:
    build:
      context: ../
      dockerfile: ./docker_builds/DockerFile
    container_name: routine
    expose:
      - "8080"
    depends_on:
      - routine_db
      - routine_redis
    networks:
      - routine_net

  routine_nginx:
    build:
      context: ../
      dockerfile: ./docker_builds/DockerFileNginx
    container_name: routineNginx
    ports:
      - "8002:80"
    depends_on:
      - routine
    networks:
      - routine_net

  routine_redis:
    image: redis:7.0.5
    container_name: routineRedis
    expose:
      - "6379"
    networks:
      - routine_net

networks:
  routine_net:
    driver: bridge
